name: Publish Docker Image

on:
    push:
        branches:
            - main

jobs:
    docker:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v4
    
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -
                name: Set environment variables
                run: |
                    rm -rf .env
                    echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
                    echo "DB_URI=${{ secrets.DB_URI }}" >> .env
                    echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
                    echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
                    echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> .env
                    echo "WASABI_ACCESS_KEY_ID=${{ secrets.WASABI_ACCESS_KEY_ID }}" >> .env
                    echo "WASABI_ACCESS_KEY_SECRET=${{ secrets.WASABI_ACCESS_KEY_SECRET }}" >> .env
                    echo "WASABI_IMAGES_BUCKET_NAME=${{ secrets.WASABI_IMAGES_BUCKET_NAME }}" >> .env
                    echo "WASABI_IMAGES_BUCKET_URI=${{ secrets.WASABI_IMAGES_BUCKET_URI }}" >> .env

            -
                name: Build docker image
                run: |
                    docker build . -t iamthewraith/wraithnet-api:latest
            
            -
                name: Push docker image
                run: |
                    docker push iamthewraith/wraithnet-api:latest                 
